### ISSUE TITLE
Allow `read-only` field

### ISSUE THREAD

**Issue by gre** [jquense/uncontrollable#3]
Hi,

I'm using uncontrollable to expose my component:
```javascript
export default uncontrollable(MyReactComponent, {
  value: "onChange"
});
```

and when trying to use that component in a "read-only" way:

```jsx
<Component value={42} />
```

I'm getting this warning:
```
Warning: Failed propType: You have provided a `value` prop to `` without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set `onChange` Check the render method of `Example`.
```

but I actually want the field to be read-only. I don't think read-only display should be disallowed.

So far, I could just ignore the warning but what annoy me then is that I can't know if the component is read-only by checking if `props.onChange` is here: onChange seems to always be provided by `uncontrollable` even if the original onChange is not provided.

Would you agree to pass `undefined` in when the initial onChange handler is `undefined`?

Regards,
gre

**Comment by jquense** [comment]
Hi there,

Thanks for the report, the rational for the propType warning is that, this utility is for creating controlled/uncontrolled components, and not readonly/disabled components, as such indicating that you want to control the component (via the value prop) but not providing a way to handle it is generally an error, and not a feature, This also mirrors the default React input behavior, which warns for a missing `onChange`. 

If you want readOnly behavior it might be better to directly support that with say, a `readOnly` prop on the component (like inputs). Alternatively, you can just provide a noop handler to the component, (like `onChange=function(){}`) which clearly indicates that you just don't want to ever change the value.

 Right now it is not simple to pass `undefined` when the onChange is left out, because we also need to handle the case for when `defaultValue` is provided, and the wrapping component needs to handle the `onChange` itself, it can be done but right now I don't want to over complicate the simplicity of this utility but i will consider it in the future.

**Comment by gre** [comment]
The fact that you do not provide an handler is enough to determine that you want **read-only** to me and it is also quite convenient. Providing such readOnly prop make things more complex and I think have inconsistencies (in your proposal readOnly, `onChange=anHandle + readOnly=true`   OR   `onChange=undefined + readOnly=false`   are non sense state representation to me).

Here is my use-case if it can helps: http://greweb.me/bezier-easing-editor/example/ 

I already forked uncontrollable into a local version and just had to make a few changes to make it work properly (and `defaultValue` seems to work fine)

I basically changed 2 things:
- removed the warning check (we can do better, see my last notes*)
- added `this.props[handle] && ` at this line: https://github.com/gre/bezier-easing-editor/blob/master/src/uncontrollable.js#L76


If it doesn't work for you I can just keep my fork and don't use uncontrollable.

**\*However:** about the warning: I think we could reconciliate the 2 needs (your use-case = the handler is required, my use-case = the handler is optional) by just **listening to the propTypes `.isRequired`**. Would that work to you?

**Comment by jquense** [comment]
I appreciate the input but I think you might misunderstand the point of this module, as your changes break the core functionality of it. 

```js
UncontrolledInput = uncontrollable(MyReactComponent, {
  value: "onChange"
});
<UncontrolledInput defaultValue='uht o, this will never change'/>
```

The above example is broken with your change. Without the `setAndNotify` the wrapped input cannot manage the value prop in state, because it isn't listening for `onChange` on `MyReactComponent`. 

I am honestly not able to gather from your example why you even need this module, as it seems like you just want the default behavior for `value/onChange`. In which case `<MyReactComponent value='hi'/>` already does what you want without needing to wrap it with uncontrollable.

As I said above, If you do want to use it, your use case can be solved without any changes by just providing a noop handler.

```js
UncontrolledInput = uncontrollable(MyReactComponent, { value: "onChange" });

<UncontrolledInput value='hi' onChange={()=>{}}/>
```

**Comment by gre** [comment]
![screen shot 2015-03-30 at 18 17 11](https://cloud.githubusercontent.com/assets/211411/6900755/0466cb44-d709-11e4-9460-8fd342429dd0.png)

notice how I don't have handles here (onChange is not provided so the input is considered `disabled` (read-only) ).

I can't reproduce the fact that defaultValue is not working (maybe I miss your point of breaking the core functionally but I can't reproduce the issue on my side). For me it seems that `value` is properly initialized by `defaultValue` (on my example, it is the "Uncontrolled Bezier Editor" on the right, the value is randomized on page load, see how it is sync at beginning but when you change the controlled value (left) it doesn't get controlled).

```javascript
      <BezierEditor
        defaultValue={value}
        onChange={this.onChange}
        ...>
      <text x={0} y={16} fill="#33a">Uncontrolled Bezier Editor</text>
    </BezierEditor>
```

I guess I can just continue with my fork. I really wish we could satisfy the 3 use-cases:
- making a controlled input
- making an uncontrolled input
- making a disabled input

like it would be possible using React `< input />`

Also I understand that you don't want to overcomplicate the library

**Comment by jquense** [comment]
It seems like you can't reproduce the behavior because you are providing an `onChange` handler with the default value, in my example it was omitted.

Ultimately I don't think that this modules job to create disabled/readonly inputs, I recognize that as a valid need, but I don't want to add complexity when it can be solved elsewhere.

Like I said you really don't need to fork it (though you are of course welcome to), you can get the behavior you want but just providing a handler that doesn't do anything. If you don't want to expose that to consumers, then just wrap the component again,

```jsx
UncontrolledInput = uncontrollable(MyReactComponent, { value: "onChange" });

return React.CreateClass({
 render(){
  return <UncontrolledInput {...this.props} onChange={this.props.onChange || ()=>{} }/>
 }
})
```

Thanks again for talking the time to submit this and talk through it. If in the future I feel like this is something i'd want to add i'll reference this issue.

**Comment by gre** [comment]
I understand your effort on having a simple library.

I don't 100% follow the idea that a warning will always be logged even when the PropType is not `isRequired`. Because the library seems to implicitely consider not providing an handler to be ok *(it doesn't break, just a warning. and on your component you will have a fallbacked handler)*.

> It seems like you can't reproduce the behavior because you are providing an onChange handler with the default value, in my example it was omitted...in any case that's not the point

You are right, I haven't tested the defaultValue with no onChange callback.

> you can get the behavior you want but just providing a handler that doesn't do anything

Actually I can't get the behavior I want (without introducing another way to enable the readOnly). because I don't know if the original `onChange` was provided if you always fallback with `||()=>()`. So I cannot branch the UI based on that.

---

I guess I will go back a simpler implementation where I manage a "value" state myself inside the component itself (which is ~ ok with just one value to hold).

Thanks

**Comment by jquense** [comment]
> I don't 100% follow the idea that a warning will always be logged even when the PropType is not isRequired. 

It mirrors the behavior of the normal React input components (`<input/>`, `<select/>`, and `<textarea/>`) which warn when you leave out the `onChange` but include a `value`, more broadly because including a `value` indicates that you want to be in charge of that `prop`, but are missing the other half of that.

> Actually I can't get the behavior I want (without introducing another way to enable the readOnly). because I don't know if the original onChange was provided if you always fallback with ||()=>(). So I cannot branch the UI based on that.

Sorry I'm not sure I understand, the "readonly" would only for the `value` prop, there shouldn't be any need for the base `MyReactComponent` to test for the existence of `onChange` because it is never managing the value of `value`. All it needs to do is call `onChange` when it wants a change, in this case it will call an empty function and no new value will be set, rendering the `value` prop (but not the entire component) readOnly.

If you want broader "component-wide" readonly behavior then you really should provide a `readOnly` prop (in my opinion). This is how the normal `<input/>`, `<select/>`, and `<textarea/>` components work in React. You can provide an `onChange` handler, but if its `readOnly` the value never changes and so the handler never fires.
```jsx
<input type='text' readOnly value="hi" onChange={this.handle}/>
```
This decouples the listening for an event from specifying behavior. Sometimes those overlap (as in your case) but many times they do not.

**Comment by gre** [comment]
Oh OK sounds good, sorry I totally messed up on what I thought to be react
conventions. My mistake.

I'll just stick to those react conventions with readonly prop then.
Providing at least an empty callback is the price to pay i guess. readOnly
can be checked in order to disable the UX and the onChange would never get
called by that disabled UX.
I guess nice part of it is you just have to switch readOnly on or off to
update that behavior.

Sounds good. Thanks for your time and sorry for misunderstanding you.
Cheers
